### PR TITLE
Allow game forcing

### PR DESCRIPTION
**Pull request by AyeTSG**
Allow users to over-write the auto-detected game set by FModel. This will allow any user to operate FModel in any folder under a certain game type. This also addresses issues I brought up in #288.

### CODE REVIEW

**Comment by AyeTSG** [comment]
oops, previous commit had CUE4 out of sync with latest. Fixed.

**Comment by AyeTSG** [comment]
requesting review from @iAmAsval to be merged into the `dev` branch.

**Comment by 4sval** [comment]
sorry to bring this so late but I'm having a hard time understanding the use

forcing fmodel to use a specific FGame sounds useless to me
the only thing I can think of is revealing hidden buttons for Fortnite such as the map viewer and mappings
for every other game, it has no use except confusion when switching games

it looks kinda overkill when there are 2 other solutions

1. having a properly formatted pak folder like so `/FGame Name/Content/` (should always be the case when loading a game) (friendly reminder we don't officially support old game versions)
2. uncomment [this](https://github.com/4sval/FModel/blob/dev/FModel/ViewModels/CUE4ParseViewModel.cs#L286) (I don't remember why it got commented) (might come too late to update the controls idk)

**Comment by GMatrixGames** [comment]
Main reason I merged this, is because of the fact that many times while trying to look into compat for odd games, I find only downloads of paks with no structure. Happened when I was testing Sea of Thieves, and I didn't know "Athena" was the game name, even though there was overrides for meshes and such for that game.

There's many instances where you might not know the full root game name, if you're just datamining games without the full download, regardless of old Fortnite versions. Also, this could be expanded on to support a custom FGame name entry for games that aren't already supported by FModel, without having to add an FGame enum entry.

Just some thoughts on it.

**Comment by 4sval** [comment]
Yea I get the point that the enum is limiting a lot of things, settings wise
Atm it's impossible to use different settings on different versions of the same game because of it
Would have been better to make it based on a path instead, but unfortunately, v4 has been built with the enum

Still, in the end, we talk about FGame, not the UE version
It's only used for

- ~~Settings between games~~ <sub>can be reworked, might fix the root issue and more</sub>
  - ~~AES~~
  - ~~Game Presets~~ <sub>Fortnite</sub>
  - ~~UE Version~~
  - ~~Custom Dirs~~
- Game Icons
  - Fortnite
  - Battle Breakers <sub>who cares?</sub>
  - Spellbreak <sub>who cares?</sub>
- Mappings <sub>Fortnite</sub>
- Hotfixed Strings <sub>Fortnite latest only</sub>
- Texture Channels
  - Fortnite
  - Valorant
  - GTA
- Discord RPC
- Hidden Tabs / Buttons <sub>Fortnite</sub>
- Window Title

So yea I just don't understand the effort on forcing the FGame
Getting the overwrite mappings button? our custom directories back? fancy rpc?

**Comment by 4sval** [comment]
requesting more explanation from @AyeTSG to actually publish the feature.

**Comment by AyeTSG** [comment]
> requesting more explanation from @AyeTSG to actually publish the feature.

Hi, I implemented this as I host a public database of past Fortnite event packages, with instructions on how to use them properly with FModel. Before this commit, there was no way to just extract the packages to the folder, and have FModel read them as FortniteGame packages. This commit is intended to solve the edge-use case of users having packages in standalone folders able to use FModel as intended.

**Comment by 4sval** [comment]
so it's basically to show hidden buttons, isn't it?

**Comment by 4sval** [comment]
> 2. uncomment [this](https://github.com/4sval/FModel/blob/dev/FModel/ViewModels/CUE4ParseViewModel.cs#L286) (I don't remember why it got commented) (might come too late to update the controls idk)

then only this was needed, but it comes with 2 cons

1. window title will stay like so `FModel {Update} - Unknown ({UE})` <sub>not a big deal imo</sub>
2. settings will still use FGame.Unknown <sub>at least it doesn't mess with the latest game version</sub>

**Comment by AyeTSG** [comment]
> > 2. uncomment [this](https://github.com/4sval/FModel/blob/dev/FModel/ViewModels/CUE4ParseViewModel.cs#L281) (I don't remember why it got commented) (might come too late to update the controls idk)
> 
> then, only this was needed, but it comes with 2 cons as of now
> 
> 1. window title will stay like so `FModel {Update} - Unknown ({UE})` <sub>not a big deal imo</sub>
> 2. settings will still use FGame.Unknown <sub>at least it doesn't mess with the latest game version</sub>

This would only happen if the user enables game forcing, and forces the 'Unknown' FGame.

**Comment by 4sval** [comment]
I mean it's either one or the other
I personally am not for such a setting because

- it's pretty confusing user-wise
- as already said, looks overkill for only making the overwrite mapping option appear (other fn related options are not update-proof anyway)

but if it has to stay, it will stay.
what would be the solution to me is uncommenting the said line (or just making 2 folders like expected, doesn't hurt) and to fix the 2 cons, I would completely erase any FGame thing from the code

1. making the window show the internal game name
2. making settings game path sensitive

but this comes with its own problems

- no more pre-filled custom directories
- no more pre-set UE version
- these two are fixable but not pretty
```c#
public EGame GetUEVer(string path)
{
    if (!_overridedGame.TryGetValue(path, out var ver))
        return ver;

    var game = GetGameFromPath(path); // require proper folder structure
    switch (game)
    {
        // imagine this with custom dirs
        case "FortniteGame": return EGame.GAME_UE5_LATEST;
        case "ShooterGame": return EGame.GAME_Valorant;
        ...
        default: return EGame.GAME_UE4_LATEST;
    }
}
```
- a setting migration to support game paths instead of FGame, to keep until a future, setting reset worth, update
- probably a lot of UI parameters to change

---

in the end, that mess is one of the many reasons why I hate having to deal with outdated game versions

**Pull request merged**
