### PR TITLE
Add Dead by Daylight detection

### PR DESCRIPTION
**Pull request by BrandonItaly**
Dead by Daylight game detection

### CODE REVIEW

**Comment by GMatrixGames** [comment]
This PR requires the remaining information to be added like the name converter, and default versioning values in UserSettings

**Comment by BrandonItaly** [comment]
This information already exists for Dead By Daylight in the UserSettings

**Comment by GMatrixGames** [comment]
It may exist for the default UE versions, I missed that, but doesn't exist
for the game name converter

**Comment by BrandonItaly** [comment]
Should be good now

**Pull request merged**
