### PR TITLE
Update EnumExtensions.cs

### PR DESCRIPTION
**Pull request by sirvibegodlol**

### CODE REVIEW

**Comment by NotOfficer** [comment]
cringe

**Comment by sirvibegodlol** [comment]
>In my defense,it wasn't supposed to push I did the wrong thing

**Comment by NotOfficer** [comment]
ah ok so creating the PR was also an accident?

**Comment by sirvibegodlol** [comment]
> ah ok so creating the PR was also an accident?

I was trying to fork the repository but I did it entirely wrong...I was changing a random file so It would create a forked repo which I didn't need to do

**Pull request closed without merging**
