### PR TITLE
Automatic AES Support

### PR DESCRIPTION
**Pull request by nickgeiserr**
Adds Minecraft Dungeons Automatic AES support

### CODE REVIEW

**Comment by Tectors** [comment]
> > It is however pointing to your own github, what's the aes coming from?
> 
> from the link

Yes, I know but what is that coming from, the AES key where did you get that from.

**Comment by sirvibegodlol** [comment]
> > > It is however pointing to your own github, what's the aes coming from?
> > 
> > 
> > from the link
> 
> Yes, I know but what is that coming from, the AES key where did you get that from.

oh, I just get it whenever a new update is released and put it into the repo

**Comment by Tectors** [comment]
> how do you automate it? does it need a system that can get the new aes key every time an update releases without any help from any humans? Is there any Open-Source examples of this anywhere?

if there's nothing on it then tell us how you did it genius

**Comment by sirvibegodlol** [comment]
bro what? I was asking a question on how to automate it and if there were any examples of it I could look at. I never said I could do it

**Comment by Amrsatrio** [comment]
What if we integrate an AES finder into FModel? That'd be a win-win solution.

**Comment by FabianFG** [comment]
> What if we integrate an AES finder into FModel? That'd be a win-win solution.

Not that hard actually

**Pull request closed without merging**
