### PR TITLE
[WIP] built in aes key grabber so fmodel doesnt die on update nights

### PR DESCRIPTION
**Pull request by OutTheShade**
how it works:

1. download shipping launcher from manifest

2. launch shipping launcher and scan for the aes pattern 

3. profit

work still needs to be done on the code to make it more fluid with fmodel but this rough version works

### CODE REVIEW

**Comment by GMatrixGames** [comment]
Marking this as WIP so it shouldn't be merged yet

**Comment by iAmAsval** [comment]
*yet*

**Comment by FabianFG** [comment]
The plan is to make mappings generation also built-in so potentially these two will merge together.

**Comment by FabianFG** [comment]
Also it's possible to do it without a native launcher and also your way of ensuring that the game started properly isn't secure. It wouldn't work on older builds that take ages to unpack. That's all stuff that is fixable though. Will work on that.

**Comment by Tectors** [comment]
Before we merge this branch we also have to make FModel fix its self's code without a human doing anything, so it won't break on a major update.

**Comment by sirvibegodlol** [comment]
smart smart smart.

**Review by Harley2787 — APPROVED** [review]

**Comment by KyeOnDiscord** [comment]
The pattern scan code you sent opens a handle which can be detected by easy anti cheat. (I'm pretty sure EAC removes the handle), so the code might not work

**Comment by NotOfficer** [comment]
> 

EAC doesnt even get launched :bonk:

**Comment by OutTheShade** [comment]
not like this code even works or matters anymore. not sure if it works on other UE games tho..

**Comment by KyeOnDiscord** [comment]
oh i didn't know which executable has the aes key, i just assumed it was in the main game process.

**Comment by OutTheShade** [comment]
just tested it and it might not even be useable at all cuz the new win shipping file doesnt even give an error box anymore it just launches EGL

**Pull request closed without merging**
