### PR TITLE
useless function call

### PR DESCRIPTION
**Pull request by Krowe-moh**

### CODE REVIEW

**Comment by NotOfficer** [comment]
what?

**Comment by Krowe-moh** [comment]
the function is called two times

**Comment by Krowe-moh** [comment]
image

**Comment by NotOfficer** [comment]
> the function is called two times

oh i see, i got confused why you changed `.Count != 0` to `.Any()`

**Comment by Krowe-moh** [comment]
when i was using the preformance profiler it said that operations reduced when using `.Any()`

**Comment by NotOfficer** [comment]
> when i was using the preformance profiler it said that operations reduced when using `.Any()`

that makes no sense. `Count/Length != 0` is always "better" than the linq "Any()" function. its not a big deal but just pointed this out. will merge with these changes reverted 👍

**Comment by Krowe-moh** [comment]
🤷‍♂️

**Pull request merged**
