### PR TITLE
Basic bookmarks support

### PR DESCRIPTION
**Pull request by Kein**

### CODE REVIEW

**Comment by ryantheleach** [comment]
You are going to need to pitch this a little harder unless you have discussed it somewhere in private, as FModel already has rudimentary bookmarking support via saved directories under the Packages menu:

image

**Comment by Kein** [comment]
I'm not pitching anything. The directory support has nothing to do with bookmark support as it is only game specific for specific opened path (game). Bookmarks bookmark game directories so you can easily swap between different opened games (multiple version or just multiple different games).

**Comment by GMatrixGames** [comment]
As you can add custom game paths to the game selection menu, I don't see how this is useful, unless I'm missing the point of "Bookmarks"

**Comment by ryantheleach** [comment]
> as it is only game specific for specific opened path (game).

This was surprising behavior to me, and after you said it I swore it was wrong.

So I checked it in FModel.

I have custom games saved, and I'm not sure how it happened but I've seemingly got 1 directory that works fine when switching the path to point at a backup of a previous version, but one that does indeed seem to toggle.

Your UI for bookmarks may be better, but as someone who has handled PR merging for other open source projects in the past, unless discussed privately you tend to need to put more work into your original post, to 1. show visually (if there are any visual differences) in what you are doing. and 2. advocate on why it's a better solution then next nearest thing. 

Because without checking out the code, reverse engineering it from source to understand it's purpose, maintainers usually just won't waste their time with a pull request that has zero info in the post.

Motives also can't be determined from code.

Maintainers arn't mind-readers, but it's not 100% my place to comment.

But I would like to see improvements to how bookmarks / directories are handled in FModel, and see this contribution at a point where it could be merged, but I just couldn't see it happening without you providing details.

Please don't take this as an attack, and view it from the other side for a moment.

**Comment by ryantheleach** [comment]
> Bookmarks is for saving game directories so you can easily swap between different opened games (multiple version or just multiple different games)

I could see this as being useful, but this is the information /justification you needed, with screenshots, in the first post.

Considering that other games can just be added as games, and directories are supposed to be per game, (and not necessarially per path).

I'd 
1. rework directories to be per-game and ignore the path.
2. rename 'bookmarks' to be 'versions', so you have multiple paths for the same game, in different directories, with the ability to change versions easily.

**Comment by Kein** [comment]
You don't need to do anything, you can just close the PR. I'm not gonna spend whole week of in back and forth discussion as If I'm working on my dissertation to CONVINCE you in the need for functionality. I made it for myself because FModel  had no such usability and in the supposed spirit of OSD I have contributed in a way I could.

**Comment by ryantheleach** [comment]
I'm not in a position to close the PR, I too was hoping to get some useable improvement out of this into FModel, that matches how the current application works, instead of it being closed the next time the maintainers had time to because it had no accompanying post.

**Pull request closed without merging**
